[package]
name = "mibar-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
smithay-client-toolkit = "0.18.0"
tiny-skia = "0.11.1"
nohash = "0.2.0"
ahash = "0.8.3"
cosmic-text = "0.9.0"
lru = { version = "0.11.0", default-features = false }
lazy_static = "1.4.0"
